services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=keyboard
        ports:
            - 5555:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
